
export const PROGRESS = "PROGRESS";

export const SET_RESUME_DETAILS = "SET_RESUME_DETAILS";

export const SET_EDUCATION_DETAILS = "SET_EDUCATION_DETAILS";

export const SET_SKILLS = "SET_SKILLS";

export const SET_PROJECTS = "SET_PROJECTS";

export const SET_EXPERIENCE_DETAILS = "SET_EXPERIENCE_DETAILS";

export const SET_INTENSHIP_DETAILS = "SET_INTENSHIP_DETAILS" ;   

export const SET_CERTIFICATES = "SET_CERTIFICATES";

export const SET_LANGUAGES = "SET_LANGUAGES";

export const SET_SOCIAL_LINKS = "SET_SOCIAL_LINKS";

export const SET_PHOTO = "SET_PHOTO";


